name: 'efti'

services:
  alb:
    image: nginx
    ports:
      - 127.0.0.1:8888:443
    extra_hosts:
      - "host.containers.internal:host-gateway"
    volumes:
      - type: bind
        source: ./alb/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
      - type: bind
        source: ./alb/certificates
        target: /etc/nginx/certificates
        read_only: true

  db:
    image: postgres:15
    command: postgres -c 'max_connections=500'
    volumes:
      - type: bind
        source: ./initdb
        target: /docker-entrypoint-initdb.d
        read_only: true
    ports:
      - 127.0.0.1:8432:5432
    environment:
      POSTGRES_PASSWORD: efti

  admin:
    image: dpage/pgadmin4
    ports:
      - 127.0.0.1:8090:80
    environment:
      PGADMIN_DEFAULT_PASSWORD: efti
      PGADMIN_DEFAULT_EMAIL: efti@solita.fi

  mock-platform:
    build: ../mock-platform
    ports:
      - '127.0.0.1:8091:8091'
    volumes:
      - ../mock-platform/data/:/var/data/
    environment:
      MOCK_PLATFORM_DATA_DIR: /var/data/

  edelivery-ap-fi1:
    image: efti/harmony:latest
    depends_on:
      - edelivery-db-fi1
    env_file:
      - harmony/fi1/.env
    environment:
      - DB_HOST=edelivery-db-fi1
      - DB_SCHEMA=harmony_ap
      - DB_PASSWORD=efti
      - ADMIN_PASSWORD=efti
      - EFTI_PMODE_ADMIN_PASSWORD=efti_pmode
      - DOMIBUS_PLUGIN_PASSWORDPOLICY_PATTERN=^.+$
      - USE_DYNAMIC_DISCOVERY=false
      - PARTY_NAME=fi1
      - SERVER_FQDN=edelivery-ap-fi1
      - SECURITY_KEYSTORE_PASSWORD=ap-keystore-fi1
      - SECURITY_TRUSTSTORE_PASSWORD=ap-truststore-fi1
      - TLS_KEYSTORE_PASSWORD=tls-keystore-fi1
      - TLS_TRUSTSTORE_PASSWORD=tls-truststore-fi1
      - DOMIBUS_AUTH_UNSECURELOGINALLOWED=true
    ports:
      - "127.0.0.1:8443:8443"
    extra_hosts:
      - "host.containers.internal:host-gateway"
    mem_limit: 1500m

  edelivery-db-fi1:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=efti
      - MYSQL_DATABASE=harmony_ap
      - MYSQL_USER=harmony_ap
      - MYSQL_PASSWORD=efti
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_bin"
    mem_limit: 512m

  edelivery-ap-fi2:
    image: efti/harmony:latest
    depends_on:
      - edelivery-db-fi2
    env_file:
      - harmony/fi2/.env
    environment:
      - DB_HOST=edelivery-db-fi2
      - DB_SCHEMA=harmony_ap
      - DB_PASSWORD=efti
      - ADMIN_PASSWORD=efti
      - EFTI_PMODE_ADMIN_PASSWORD=efti_pmode
      - DOMIBUS_PLUGIN_PASSWORDPOLICY_PATTERN=^.+$
      - USE_DYNAMIC_DISCOVERY=false
      - PARTY_NAME=fi2
      - SERVER_FQDN=edelivery-ap-fi2
      - SECURITY_KEYSTORE_PASSWORD=ap-keystore-fi2
      - SECURITY_TRUSTSTORE_PASSWORD=ap-truststore-fi2
      - TLS_KEYSTORE_PASSWORD=tls-keystore-fi2
      - TLS_TRUSTSTORE_PASSWORD=tls-truststore-fi2
      - DOMIBUS_AUTH_UNSECURELOGINALLOWED=true
    ports:
      - "127.0.0.1:8444:8443"
    mem_limit: 1500m

  edelivery-db-fi2:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=efti
      - MYSQL_DATABASE=harmony_ap
      - MYSQL_USER=harmony_ap
      - MYSQL_PASSWORD=efti
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_bin"
    mem_limit: 512m

  gate-fi2:
    image: efti/backend:latest
    env_file: gate-fi2.env
    extra_hosts:
      - "host.containers.internal:host-gateway"

  edelivery-ap-fi3:
    image: efti/harmony:latest
    profiles: [test-fest]
    depends_on:
      - edelivery-db-fi3
    env_file:
      - harmony/fi3/.env
    environment:
      - DB_HOST=edelivery-db-fi3
      - DB_SCHEMA=harmony_ap
      - DB_PASSWORD=efti
      - ADMIN_PASSWORD=efti
      - EFTI_PMODE_ADMIN_PASSWORD=efti_pmode
      - DOMIBUS_PLUGIN_PASSWORDPOLICY_PATTERN=^.+$
      - USE_DYNAMIC_DISCOVERY=false
      - PARTY_NAME=eu-fi3
      - SERVER_FQDN=edelivery-ap-fi3
      - SECURITY_KEYSTORE_PASSWORD=efti
      - SECURITY_TRUSTSTORE_PASSWORD=changeit
      - TLS_KEYSTORE_PASSWORD=efti
      - TLS_TRUSTSTORE_PASSWORD=changeit
      - DOMIBUS_AUTH_UNSECURELOGINALLOWED=true
      - EXTERNAL_LB=true
    ports:
      - "127.0.0.1:8443:8080"
      - "192.168.0.105:8443:8080"
    extra_hosts:
      - "host.containers.internal:host-gateway"
      - "eu-fi1.efti.eu:192.168.0.104"
      - "eu-fi2.efti.eu:192.168.0.101"
      - "domibus.fr:192.168.0.102"
    mem_limit: 1500m

  edelivery-db-fi3:
    image: mysql:8
    profiles: [test-fest]
    environment:
      - MYSQL_ROOT_PASSWORD=efti
      - MYSQL_DATABASE=harmony_ap
      - MYSQL_USER=harmony_ap
      - MYSQL_PASSWORD=efti
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_bin"
    mem_limit: 512m

volumes:
  data:
