name: 'efti'

services:
  alb:
    image: nginx
    ports:
      - 127.0.0.1:8888:443
    extra_hosts:
      - "host.containers.internal:host-gateway"
    volumes:
      - type: bind
        source: ./alb/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
      - type: bind
        source: ./alb/certificates
        target: /etc/nginx/certificates
        read_only: true

  db:
    image: postgres:15
    command: postgres -c 'max_connections=500'
    volumes:
      - type: bind
        source: ./initdb
        target: /docker-entrypoint-initdb.d
        read_only: true
    ports:
      - 127.0.0.1:8432:5432
    environment:
      POSTGRES_PASSWORD: efti

  admin:
    image: dpage/pgadmin4
    ports:
      - 127.0.0.1:8090:80
    environment:
      PGADMIN_DEFAULT_PASSWORD: efti
      PGADMIN_DEFAULT_EMAIL: efti@solita.fi

  mock-platform:
    build: ../mock-platform
    restart: always
    ports:
      - '127.0.0.1:8091:8091'
    volumes:
      - ../mock-platform/data/:/var/data/
    environment:
      MOCK_PLATFORM_DATA_DIR: /var/data/

  harmony-ap-fi:
    image: efti/harmony
    depends_on:
      - harmony-db-fi
    env_file:
      - harmony/fi/.env
    environment:
      - DB_HOST=harmony-db-fi
      - DB_SCHEMA=harmony_ap
      - DB_PASSWORD=efti
      - ADMIN_PASSWORD=efti
      - EFTI_PMODE_ADMIN_PASSWORD=efti_pmode
      - DOMIBUS_PLUGIN_PASSWORDPOLICY_PATTERN=^.+$
      - USE_DYNAMIC_DISCOVERY=false
      - PARTY_NAME=fi_1_efti
      - SERVER_FQDN=harmony-ap-fi
      - SECURITY_KEYSTORE_PASSWORD=efti1234
      - SECURITY_TRUSTSTORE_PASSWORD=efti1234
      - TLS_KEYSTORE_PASSWORD=efti1234
      - TLS_TRUSTSTORE_PASSWORD=efti1234
      - DOMIBUS_AUTH_UNSECURELOGINALLOWED=true
    ports:
      - "127.0.0.1:8443:8443"
    extra_hosts:
      - "host.containers.internal:host-gateway"
    restart: on-failure
    mem_limit: 1500m

  harmony-db-fi:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=efti
      - MYSQL_DATABASE=harmony_ap
      - MYSQL_USER=harmony_ap
      - MYSQL_PASSWORD=efti
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_bin"
    restart: on-failure
    mem_limit: 512m

  harmony-ap-se:
    image: efti/harmony
    depends_on:
      - harmony-db-se
    env_file:
      - harmony/se/.env
    environment:
      - DB_HOST=harmony-db-se
      - DB_SCHEMA=harmony_ap
      - DB_PASSWORD=efti
      - ADMIN_PASSWORD=efti
      - EFTI_PMODE_ADMIN_PASSWORD=efti_pmode
      - DOMIBUS_PLUGIN_PASSWORDPOLICY_PATTERN=^.+$
      - USE_DYNAMIC_DISCOVERY=false
      - PARTY_NAME=se_1_efti
      - SERVER_FQDN=harmony-ap-se
      - SECURITY_KEYSTORE_PASSWORD=efti1234
      - SECURITY_TRUSTSTORE_PASSWORD=efti1234
      - TLS_KEYSTORE_PASSWORD=efti1234
      - TLS_TRUSTSTORE_PASSWORD=efti1234
      - DOMIBUS_AUTH_UNSECURELOGINALLOWED=true
    ports:
      - "127.0.0.1:8444:8443"
    restart: on-failure
    mem_limit: 1500m

  harmony-db-se:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=efti
      - MYSQL_DATABASE=harmony_ap
      - MYSQL_USER=harmony_ap
      - MYSQL_PASSWORD=efti
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_bin"
    restart: on-failure
    mem_limit: 512m

  gate-se:
    image: efti/backend:latest
    env_file: gate-se.env

volumes:
  data:
