version: '3.7'
name: 'efti'

services:
  db:
    image: postgres:15
    command: postgres -c 'max_connections=500'
    volumes:
      - type: bind
        source: ./initdb
        target: /docker-entrypoint-initdb.d
        read_only: true
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_PASSWORD: efti

  admin:
    image: dpage/pgadmin4
    ports:
      - 127.0.0.1:9090:80
    environment:
      PGADMIN_DEFAULT_PASSWORD: efti
      PGADMIN_DEFAULT_EMAIL: efti@solita.fi

  mock-platform:
    build: ../mock-platform
    restart: always
    ports:
      - '127.0.0.1:9091:9091'
    volumes:
      - ../mock-platform/data/:/var/data/
    environment:
      MOCK_PLATFORM_DATA_DIR: /var/data/

volumes:
  data:
