version: '3.7'
name: 'efti'

services:
  alb:
    image: nginx
    ports:
      - 127.0.0.1:8888:443
    extra_hosts:
      - "host.containers.internal:host-gateway"
    volumes:
      - type: bind
        source: ./alb/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
      - type: bind
        source: ./alb/certificates
        target: /etc/nginx/certificates
        read_only: true

  db:
    image: postgres:15
    command: postgres -c 'max_connections=500'
    volumes:
      - type: bind
        source: ./initdb
        target: /docker-entrypoint-initdb.d
        read_only: true
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_PASSWORD: efti

  admin:
    image: dpage/pgadmin4
    ports:
      - 127.0.0.1:9090:80
    environment:
      PGADMIN_DEFAULT_PASSWORD: efti
      PGADMIN_DEFAULT_EMAIL: efti@solita.fi

  mock-platform:
    build: ../mock-platform
    restart: always
    ports:
      - '127.0.0.1:9091:9091'
    volumes:
      - ../mock-platform/data/:/var/data/
    environment:
      MOCK_PLATFORM_DATA_DIR: /var/data/

volumes:
  data:
