name: "Setup JDK"
description: "Installs JDK"
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        architecture: x64
