create table consignment (
  id                 integer generated by default as identity primary key,
  -- UIL
  gate_url           text not null,
  platform_url       text not null,
  data_id            text not null,

  is_dangerous_goods boolean,
  journey_start_time timestamptz,
  journey_end_time   timestamptz,
  country_start_id   text references country (id),
  country_end_id     text references country (id)
);

create unique index on consignment (gate_url, platform_url, data_id);