name: "Setup Clojure"
description: "Installs Clojure tools"
runs:
  using: 'composite'
  steps:
    - name: Download clojure
      run: |
        curl -L -O https://github.com/clojure/brew-install/releases/latest/download/linux-install.sh
        chmod +x linux-install.sh
        sudo ./linux-install.sh
      shell: bash