name: Build

on:
  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]
  workflow_call:
    secrets:
        AWS_DEPLOY_ROLE:
            required: true
            description: "The ARN of the role to assume for deployment"
        AWS_POC_ACCOUNT:
            required: true
            description: "The account number of the POC account"
env:
  AWS_REGION: "eu-west-1"
  ECR_REPOSITORY_DB: "efti/db"
  ECR_REPOSITORY_BACKEND: "efti/backend"

permissions:
  id-token: write
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-jdk
      - name: Install Clojure
        uses: ./.github/actions/install-clj
      - name: Cache Clojure dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
          # List all files containing dependencies:
          key: cljdeps-${{ hashFiles('deps.edn') }}
          restore-keys: cljdeps-

      - uses: ./.github/actions/aws-ecr-login
        with:
          AWS_DEPLOY_ROLE: ${{ secrets.AWS_DEPLOY_ROLE }}

      - name: Pull harmony image for tests
        run: |
          docker pull ${{ secrets.AWS_POC_ACCOUNT }}.dkr.ecr.eu-west-1.amazonaws.com/efti/harmony:latest
          docker tag ${{ secrets.AWS_POC_ACCOUNT }}.dkr.ecr.eu-west-1.amazonaws.com/efti/harmony:latest efti/harmony:latest

      - name: Start database
        run: ./start.sh
        working-directory: ./docker

      - name: Run tests
        working-directory: ./backend
        run: clojure -A:dev -A:test

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE }}
          role-session-name: githubdeploymentsession
          aws-region: ${{ env.AWS_REGION }}

      - id: login-ecr
        uses: ./.github/actions/aws-ecr-login
        with:
          AWS_DEPLOY_ROLE: ${{ secrets.AWS_DEPLOY_ROLE }}

      - name: Build db migration tool image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        working-directory: ./db
        run: |
          ./build-docker-image.sh $ECR_REGISTRY
          docker push $ECR_REGISTRY/$ECR_REPOSITORY_DB:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY_DB:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - uses: ./.github/actions/install-jdk
      - name: Install Clojure
        uses: ./.github/actions/install-clj

      - name: Build application image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        working-directory: ./backend
        run: |
          ./build-docker-image.sh $ECR_REGISTRY
          docker push $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY_DB:$IMAGE_TAG" >> $GITHUB_OUTPUT
