name: Outdated dependencies
on:
  push:
    branches:
      - feature/efti-185
    # schedule:
    #   - cron: '0 8 * * 1'
    workflow_dispatch:
jobs:
  nvd:
    container:
      image: clojure:tools-deps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v4
        with:
          key: cljdeps-${{ hashFiles('backend/deps.edn') }}
          path: |
            ~/.m2/repository
            ~/.gitlibs/
            ~/.deps.clj
      - run: ./nvd/nvd-vulnerability-scan.sh
