name: Outdated dependencies
on:
  push:
    branches:
      - main
      - feature/efti-185
  schedule:
    - cron: '0 8 * * 1'
  workflow_dispatch:
jobs:
  nvd:
    container:
      image: clojure:tools-deps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v4
        with:
          key: cljdeps-${{ hashFiles('backend/deps.edn') }}
          save-always: true
          path: |
            ~/.m2/repository
            ~/.gitlibs/
            ~/.deps.clj
      - name: NVD check
        run: ./nvd-vulnerability-scan.sh
        working-directory: ./nvd
