name: Outdated dependencies
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 8 * * 1'
  workflow_dispatch:
jobs:
  nvd:
    container:
      image: clojure:tools-deps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          key: cljdeps-${{ hashFiles('backend/deps.edn') }}
          save-always: true
          # user.home (/etc/passwd) in Docker container points to /root
          path: |
            /root/.m2/repository
            /root/.gitlibs
            /root/.deps.clj
      - name: NVD check
        run: ./nvd-vulnerability-scan.sh
        working-directory: ./nvd
